### ISSUE TITLE
"Effect Bass 1" appears twice

### ISSUE THREAD

**Issue by zOadT** [TerryCavanagh/boscaceoil#23]
Hello Terry,

first off, thanks for Bosca Ceoil, it's a great program!

I found a small bug in version 1.99. In the Instrument-tab choose bass and you will see Effect Bass 1 appears twice. This will also cause the selection to just switch between Effect Bass 1 and Effect Bass 2 to U, once Effect Bass 1 is selected and you hit the "+" button.

Maybe you already know it (1.99 is of cause just a beta) I just want to make sure :)

regards, OadT

**Comment by TerryCavanagh** [comment]
Good catch! Fixed it right now, thanks :)
