### ISSUE TITLE
website: text in flash interface not drawing when i load shared url

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/boscaceoil#34]
<img width="760" alt="screen shot 2015-08-03 at 01 52 55" src="https://cloud.githubusercontent.com/assets/465632/9028987/7e3dcbee-3982-11e5-9d8b-13d447e6a952.png">

http://online.boscaceoil.net/#!/track/DkmRkMh797
(warning, very loud first couple of seconds)

**Comment by TerryCavanagh** [comment]
Refered to boscaceoil-online project
