### ISSUE TITLE
random track feature

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/boscaceoil#35]
function RandomInt(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}

function RandomFile (){
	dat = [];

	//* version number [1,2,3]           // (3 is the current version, less is for old versions)
	dat.push (3);

	//* swing [-10,10]                   // Swing power/direction
	dat.push (RandomInt (-10, 11));

	//* effect [0,6]                     // Global effect in use
	dat.push (RandomInt (0, 7));

	//* effectvalue [0, 100]             // Effect power
	dat.push (RandomInt (0, 101));

	//* bpm [>0]
	dat.push (RandomInt(40,240));

	//* patternlength [1-32]             // Number of notes in a pattern. Max 32.
	var patternLength = RandomInt (1, 33);
	dat.push (patternLength);

	//* barlength [>0]                   // Number of notes in a bar. Doesn't affect how a song sounds.
	dat.push (RandomInt(2,10));

	//* number of instruments [0-16]
	dat.push (16);

	for (var i=0;i<16;i++){
		dat.push (RandomInt(0,366)); //* instrument number [>0]           // Index of instrument. See APPENDIX 1
		dat.push (RandomInt(0,2));//* instrument type [0,1]            // 0 is normal, 1 is drumkit.
		dat.push (RandomInt (0,6));//* instrument palette [0,5]         // colours are: blue, purple, red, orange, green, cyan, gray
		dat.push (RandomInt(0,201));//* instrument cutoff [0,200]        // Low pass filer cutoff
		dat.push (RandomInt(0,46));//* instrument resonance [0,45]      // Low pass filer resonance
		dat.push (RandomInt(0,257));//* instrument volume [0,256]        // Instrument Volume level
	}

	//* number of patterns [>0]            // Not sure what the limit is; pretty high I think
	var trackCount = 30;
	dat.push (30);
	for (var i=0; i<30; i++) {

		//* pattern key
		dat.push(RandomInt(0,12));

        //	* pattern scale
        dat.push(RandomInt(0,14));

        //		* pattern instrument
        dat.push(RandomInt(0,16));

		//		* pattern palette
		dat.push(0);
		        			  
		//		* pattern number of notes
		var noteCount=20;
		dat.push(noteCount);
		
		//We loop over the notes
		for (var t=0;t<noteCount;t++){
			//	* note index [0-127]           // Middle C is 60.
			dat.push(RandomInt(0,128));
			
			//	* note length [>0]          
			var noteLength=RandomInt(1,8);
			dat.push(noteLength);
			
			//	* x offset in pattern [0-32]
			dat.push(RandomInt(0,patternLength-noteLength+1));
			
			//	* dummy variable               // Just a wasted zero; notes are stored as a rectangle struct
			dat.push(0);
		}	
		
		//* pattern recordfilter [0,1]     // 0 is normal, 1 is if record filter is on.
		dat.push(0);

		//if record filter is on, then loop over the following 32 times, otherwise just skip it:
		//for (j = 0; j < 32; j++) {
		//	* volume at note j
		//		* cutoff at note j
		//			* resonance at note j
		//}
	}
	
	// FINALLY, ARRANGEMENTS
	
	//* length of song in patterns
	var songLength = 400;//RandomInt(2,20);
	dat.push(songLength);

	//	* start of loop
	var loopStart=RandomInt(0,songLength);
	dat.push(0);
	//		* end of loop
	dat.push(songLength);
			
	for (var i=0; i < songLength; i++) {
		for (var j = 0; j < 8; j++) {
			if (RandomInt(0,2)==0){
				dat.push(-1);
			} else {
				dat.push(RandomInt(0,trackCount));
			}
			//*index of pattern at position i, on channel j.  // There are 8 channels!
		}
	}

	return dat;
}

//console.log("ping");
//console.log();
window.onload=function(){
	var rf = RandomFile();
	var result ="";
	for(var i=0;i<rf.length;i++){
		if (i>0){
			result=result+",";
		}
		result=result+rf[i];
	}
	window.location.href = "data:,"+result;
	//document.body.innerHTML=rf;
}

**Comment by TerryCavanagh** [comment]
I've sent you a fork!
