### ISSUE TITLE
BoscaCeoil doesn't work on Mac or in Browser

### ISSUE THREAD

**Issue by TristanP-S** [TerryCavanagh/boscaceoil#74]
It doesn't work with mac sadly, and apple send me this [link](https://support.apple.com/en-us/HT208436).
It also doesn't seem to want to work on my browser giving me this [error](https://imgur.com/a/qekKmjv).
I've never used it so far, but based on this [vid](https://youtu.be/fZeZ75gM9p4) it seems to be the exact sort of program I was looking for. Is there a fix for either one?

**Comment by TerryCavanagh** [comment]
Sorry, the last update to OSX broke a lot of older software. Fixing this is on my to-do list, but with a console port and various other work on my commercial projects needing to be done, it's unlikely that I'll be able to update Bosca Ceoil anytime soon. (As for the Browser version, that's based in Adobe Flash, which is being discontinued later this year).

Apologies!

**Comment by TristanP-S** [comment]
All good, do you know any other similar software I might be able to use instead?

**Comment by TerryCavanagh** [comment]
It's pretty different, but you might like BeepBox, which is an online music making tool with some similar inspirations and goals to Bosca Ceoil! https://beepbox.co

**Comment by TristanP-S** [comment]
That's definitely similar, but is there something with downloadable software? I often code + do stuff in areas with spotty connection and prefer software if available.

**Comment by TerryCavanagh** [comment]
I’d look into FlStudio, which is a larger, more complicated program than Bosca, but which in a lot of ways the most accessible professional level music tool. GarageBand (for OSX, made by Apple) is also very good!

**Comment by TristanP-S** [comment]
Ok, Thanks for your help.
