### ISSUE TITLE
Cannot download the Windows or MacOS versions

### ISSUE THREAD

**Issue by ariedov** [TerryCavanagh/boscaceoil#76]
Trying to download the Windows or MacOS version ends up not working with the error `TOO_MANY_REDIRECTS` in both Chrome and Firefox

This url for windows: https://www.boscaceoil.net/downloads/boscaceoil_win_v2.zip
This url for macOS: https://www.boscaceoil.net/downloads/boscaceoil_mac_v2.zip

However - downloading the Linux version works fine.

**Comment by ariedov** [comment]
Trying to open the web version also doesn't work with: `DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by TerryCavanagh** [comment]
Sorry about that - I'm in the middle of a server migration. This'll be fixed very soon - in the meantime, you can download the tool from itch here: https://terrycavanagh.itch.io/bosca-ceoil/
