### ISSUE TITLE
What is the license for exported songs?

### ISSUE THREAD

**Issue by papojari** [TerryCavanagh/boscaceoil#95]
Are songs exported with Bosca Ceoil licensed under the license of the SiON library because it uses those sounds? Can I assign a license to the exports myself?

**Comment by TerryCavanagh** [comment]
They're unlicensed - bosca ceoil makes no claim to anything created with
it.  (Which I believe is the normal expectation for tools! I'd be pretty
shocked if Adobe automatically applied a license to a picture you made in
Photoshop, for example!)
