### ISSUE TITLE
Migration to Qt or Unity/C#: Feasible? 

### ISSUE THREAD

**Issue by vlaskz** [TerryCavanagh/boscaceoil#99]
I have used Bosca Ceoil a lot and would be glad to think about creating it in a common, not  vendor locked-out language as C++; Do you all mind about sharing the concepts and code strategies and knowledge about the creation of Bosca Ceoil or creating a task-force to make this happen?

**Comment by TerryCavanagh** [comment]
The blocking issue for porting Bosca Ceoil to something else is porting the AS3 based synth SiON, which nobody has so far been able to do. You're welcome to try! (If that was done, the rest is basically trivial.) Some discussion on that here: https://github.com/TerryCavanagh/boscaceoil/issues/87

(Of course, it's always possible to make a new tool that uses Bosca's UI, but uses a different synth library - but that would probably be a whole separate project)
